CREATE TABLE IF NOT EXISTS `ledger` (
  id  BINARY(36) NOT NULL PRIMARY KEY,
  item varchar(255) NOT NULL,
  cost INT NOT NULL,
  purchase_date INT NOT NULL,
  cleared BOOLEAN DEFAULT false
) ENGINE=InnoDB DEFAULT CHARSET=utf8;