CREATE TABLE IF NOT EXISTS `short_ledger` (
  id  BINARY(36) NOT NULL PRIMARY KEY,
  users varchar(255) NOT NULL,
  created_at BIGINT NOT NULL,
  active TINYINT(1) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;